# Generated by Django 4.0.3 on 2022-04-02 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0004_room_roomstatus_alter_user_userid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='roomstatus',
            field=models.CharField(max_length=7),
        ),
    ]
