# Generated by Django 4.0.3 on 2022-04-02 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0005_alter_room_roomstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(default='', max_length=6),
            preserve_default=False,
        ),
    ]
