# Generated by Django 4.0.3 on 2022-04-02 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0008_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(max_length=23),
        ),
    ]
