# Generated by Django 4.0.3 on 2022-04-02 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0010_alter_room_roomstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='roomstatus',
            field=models.CharField(max_length=7),
        ),
    ]
