# Generated by Django 4.0.3 on 2022-04-02 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0011_alter_room_roomstatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roomid', models.CharField(max_length=6)),
                ('messagetitle', models.CharField(max_length=25)),
                ('message1users', models.CharField(max_length=90)),
                ('message2users', models.CharField(max_length=90)),
            ],
        ),
        migrations.AddField(
            model_name='room',
            name='roomfurtherstatus',
            field=models.CharField(default='normal', max_length=7),
            preserve_default=False,
        ),
    ]
