# Generated by Django 4.0.3 on 2022-04-02 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0012_message_room_roomfurtherstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='messageid',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='room',
            name='messagecount',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
