# Generated by Django 4.0.3 on 2022-04-03 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0013_message_messageid_room_messagecount'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='questcount',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='room',
            name='votetitle',
            field=models.CharField(default=False, max_length=19),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='onvote',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='voteresult',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
