# Generated by Django 4.0.3 on 2022-04-03 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0014_room_questcount_room_votetitle_user_onvote_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='voteresult',
        ),
        migrations.AddField(
            model_name='room',
            name='votecontent',
            field=models.CharField(default='', max_length=90),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='room',
            name='votetitle',
            field=models.CharField(max_length=22),
        ),
    ]
