# Generated by Django 4.0.3 on 2022-04-03 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0016_user_result'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='message1users',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='message',
            name='message2users',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='room',
            name='votecontent',
            field=models.CharField(max_length=200),
        ),
    ]
