# Generated by Django 4.0.3 on 2022-04-03 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0017_alter_message_message1users_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='teambuilder',
            field=models.CharField(default='', max_length=7),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='room',
            name='teammembercount',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='room',
            name='teammembercountnow',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
