# Generated by Django 4.0.3 on 2022-04-03 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0020_alter_message_messagetitle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='messagetitle',
            field=models.CharField(max_length=25),
        ),
    ]
